apiVersion: v1
kind: Pod
metadata:
  name: nginx-002
spec:
  containers:
  - name: nginx-002
    image: nginx:1.17.10
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      value: postgresql://mydb:5432
    - name: DB_USER
      value: admin

