
apiVersion: v1
kind: Pod
metadata:
  name: configmap-mani-pod-mounted
  labels:
    name: configmap-mani-pod-mounted
spec:
  containers:
  - name: configmap-mani-pod-mounted
    image: nginx:1.19.0
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    env:
    - name: DB_URL
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: NIADA_DB_URL
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: NIADA_DB_USER
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
  volumes: 
  - name: config-volume
    configMap:
      name: yaml-config
