
apiVersion: v1
kind: Pod
metadata:
  name: configmap-mani-pod
  labels:
    name: configmap-mani-pod
spec:
  containers:
  - name: configmap-mani-pod
    image: nginx:1.19.0
    env:
    - name: DB_URL
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: NIADA_DB_URL
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: NIADA_DB_USER
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
