apiVersion: v1
kind: Pod
metadata:
  name: secrets-mounted-pod
  labels:
    name: secrets-mounted-pod
spec:
  containers:
  - name: secrets-mounted-pod
    image: nginx:1.19.0
    volumeMounts:
    - name: secret-volume
      mountPath: /var/app
      readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9997
  volumes:
  - name: secret-volume
    secret:
      secretName: file-creds
