apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loop
  name: loop
spec:
  containers:
  - args:
    - /bin/bash
    - -c
    - |-
      for i in 1 2 3 4 5 6 7 8 9 10; \
       do echo "Welcome $i times"; done
    image: busybox:latest
    name: loop
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
