apiVersion: v1
kind: Pod
metadata:
  name: annotated-pod
  labels:
    what: annotation
  annotations:
    commit: 3ba0d44
    author: 'Papa Bosu'
    branch: 'ckad_prtc/main'
spec:
  containers:
  - name: annotated-pod
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9797
