apiVersion: v1
kind: Pod
metadata:
  name: awesome-quota-pod-2
spec:
  containers:
  - name: awesome-quota-pod-2
    image: nginx:1.18.0
    resources:
      requests:
        cpu: "0.5"
        memory: "512m"
      limits:
        cpu: "1"
        memory: "1024m"
