apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-26T01:31:34Z"
  labels:
    env: dev
    tier: backend
  name: two-labeled-pod
  namespace: default
  resourceVersion: "2599780"
  uid: 977dffef-579a-419a-b4a6-76d10125bcd8
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: two-labeled-pod
    ports:
    - containerPort: 9797
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xbwkt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-xbwkt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-26T01:31:35Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-07-26T01:31:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-07-26T01:31:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-07-26T01:31:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-07-26T01:31:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5ee313c6eec4c3f024f59077158f701acba3f9afd30452677ee6093eda0adb49
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:6af79ae5de407283dcea8b00d5c37ace95441fd58a8b1d2aa1ed93f5511bb18c
    lastState: {}
    name: two-labeled-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-07-26T01:31:35Z"
  hostIP: 192.168.65.3
  hostIPs:
  - ip: 192.168.65.3
  phase: Running
  podIP: 10.1.0.130
  podIPs:
  - ip: 10.1.0.130
  qosClass: Guaranteed
  startTime: "2024-07-26T01:31:34Z"
