apiVersion: v1
kind: Pod
metadata:
  name: secrets-pod
  labels:
    name: secrets-pod
spec:
  containers:
  - name: secrets-pod
    image: nginx:1.19.0
    envFrom:
    - secretRef:
        name: declarative-secret
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9998
