apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ssd-pod
  name: ssd-pod
spec:
  containers:
  - image: nginx
    name: ssd-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
